version: "3.8"
services:
  java:
    build: .
    ports:
      - "8080:8080"
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    tty: true
    volumes:
      - ./:/app
